# Generated by Django 5.2.8 on 2026-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('name', models.CharField(max_length=63, primary_key=True, serialize=False, verbose_name='name')),
                ('start', models.IntegerField(verbose_name='start')),
                ('increment', models.IntegerField(verbose_name='increment')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='value')),
            ],
        ),
    ]
