# Generated by Django 5.2.8 on 2026-04-09 09:52

from django.db import migrations


SEQUENCE_PREFIX = '_sq'


def forward_mysql(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return

    schema_editor.execute(
        'ALTER TABLE sequence_sequence '
        'MODIFY `name` VARCHAR(63) CHARACTER SET ascii '
        'COLLATE ascii_bin NOT NULL')


def forward_postgresql(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(
        'ALTER TABLE sequence_sequence '
        'ALTER COLUMN "name" TYPE VARCHAR(63) COLLATE "C"')

    # Migrate the data from real postgresql sequences to the django model.
    Sequence = apps.get_model('sequence', 'Sequence')
    db = schema_editor.connection.alias
    cursor = schema_editor.connection.cursor()
    cursor.execute(
        'SELECT sequencename, start_value, increment_by, last_value '
        'FROM pg_sequences '
        'WHERE sequencename LIKE %s',
        (f'{SEQUENCE_PREFIX}%',))

    migrated_names = []
    for row in cursor:
        name, start, increment, value = row
        migrated_names.append(name)
        name = name[3:]  # Strip the _sq prefix.
        Sequence.objects.using(db).create(
            name=name, start=start, increment=increment, value=value)

    for name in migrated_names:
        # Names are valid identifiers but have to be quoted to preserve case.
        cursor.execute(f'DROP SEQUENCE "{name}"')


def backward_postgresql(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    # Migrate the data from the django model to real postgresql sequences.
    Sequence = apps.get_model('sequence', 'Sequence')
    db = schema_editor.connection.alias
    cursor = schema_editor.connection.cursor()
    for sequence in Sequence.objects.using(db).all():
        cursor.execute(
            f'CREATE SEQUENCE "{SEQUENCE_PREFIX}{sequence.name}" '
            'INCREMENT %s START %s',
            (sequence.increment, sequence.start))
        if sequence.value:
            cursor.execute(
                'SELECT setval(%s, %s)',
                (f'{SEQUENCE_PREFIX}{sequence.name}', sequence.value))
        sequence.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        # Disable atomicity because MySQL is not allowed to run DDL in
        # transactions by Django.
        migrations.RunPython(
            forward_mysql, migrations.RunPython.noop, atomic=False),
        migrations.RunPython(forward_postgresql, backward_postgresql),
    ]
