[tox]
envlist = django{42,51,52}-{mysql,postgres,sqlite}

[travis:env]
DJANGO =
  4.2: django42
  5.1: django51
  5.2: django52

[testenv]
deps =
    -r{toxinidir}/tests/requirements.txt
    django42: Django~=4.2.26
    django51: Django~=5.1.14
    django52: Django~=5.2.8
    mysql: mysqlclient
    postgres: psycopg
setenv =
    PYTHONDONTWRITEBYTECODE=1
    DJANGO_SETTINGS_MODULE=testapp.settings
    mysql: DJANGO_SETTINGS_MODULE=testapp.settings_mysql
    postgres: DJANGO_SETTINGS_MODULE=testapp.settings_postgres
commands =
    pytest {posargs}

[coverage:run]
branch = True
source = osso

[pytest]
DJANGO_SETTINGS_MODULE = testapp.settings
addopts = --cov --cov-config tox.ini --cov-report term-missing:skip-covered --no-cov-on-fail --doctest-modules
pythonpath = . tests
testpaths = osso tests

filterwarnings =
    ignore:'cgi' is deprecated.*::django.*
    ignore:'locale\.getdefaultlocale' is deprecated.*::django.*
    ignore:datetime\.datetime\.utcnow\(\) is deprecated.*::django.*
